{
 "title": "CryptoStream DW",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "latest price per coin",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT symbol, argMax(price, trade_time) AS price\r\nFROM crypto.trades_raw\r\nWHERE trade_time >= now() - INTERVAL 1 MINUTE\r\nGROUP BY symbol\r\nORDER BY symbol"
    }
   ]
  },
  {
   "title": "BTC/USDT Live Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfInterval(trade_time, INTERVAL 5 second) AS time,\r\n    avg(price) AS btc_price\r\nFROM crypto.trades_raw\r\nWHERE symbol = 'btcusdt' AND $__timeFilter(trade_time)\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "ticks per second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() / 10 AS ticks_per_sec\r\nFROM crypto.trades_raw\r\nWHERE trade_time >= now() - INTERVAL 10 SECOND"
    }
   ]
  },
  {
   "title": "traded value per coin",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT symbol, sum(price * quantity) AS usd_volume\r\nFROM crypto.trades_raw\r\nWHERE trade_time >= now() - INTERVAL 15 MINUTE\r\nGROUP BY symbol\r\nORDER BY usd_volume DESC"
    }
   ]
  }
 ]
}